#!/bin/sh
################################################################################
##   ____  ____ 
##  /   /\/   / 
## /___/  \  /    Vendor: Xilinx 
## \   \   \/     Version : 1.11
##  \   \         Application : Spartan-6 FPGA GTP Transceiver Wizard
##  /   /         Filename : simulate_isim.sh
## /___/   /\     
## \   \  /  \ 
##  \___\/\___\ 
##
##
## Script SIMULATE_ISIM.SH
## Generated by Xilinx Spartan-6 FPGA GTP Transceiver Wizard

##***************************** Beginning of Script ***************************

        
mkdir work
##MGT Wrapper
vhpcomp -work work  ../../../pcs_pma_s6_gtpwizard_tile.vhd;
vhpcomp -work work  ../../../pcs_pma_s6_gtpwizard.vhd;


##Example Design modules
vhpcomp -work work  ../../example_design/frame_gen.vhd;
vhpcomp -work work  ../../example_design/frame_check.vhd;
vhpcomp -work work  ../../example_design/pcs_pma_s6_gtpwizard_top.vhd;


##Other modules
vhpcomp -work work  ../sim_reset_mgt_model.vhd;

##Testbench file
vhpcomp -work work  ../demo_tb.vhd;


#Compile and link source files
fuse work.DEMO_TB -L unisim -L secureip -o demo_tb.exe

##--Generate waveform trace--##
./demo_tb.exe -gui -tclbatch wave_isim.tcl -wdb wave_isim

